/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagIngresoSenoidal.java
 *
 * Created on 26-abr-2011, 18:34:15
 */

package tdc.primer_orden.gui;

import java.awt.Color;
import java.util.Collections;
import tdc.Utilidades;
import tdc.entidades.DataInput;
import tdc.entidades.DataInputCatalog;

/**
 *
 * @author fanky
 */
public class diagIngresoSenoidal extends javax.swing.JDialog {

    /** Creates new form diagIngresoSenoidal */
    public diagIngresoSenoidal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        default_values();
    }
    private void default_values(){
        Utilidades.setDouble(txtCteTiempo,0.1);
        Utilidades.setDouble(txtValorBase,100);
        Utilidades.setDouble(txtAmplitud, 2);
        Utilidades.setDouble(txtFrecuencia,3.18);
        actualiza_omega();
    }
    public DataInputCatalog getDatosIngresados(){
        DataInputCatalog data = new DataInputCatalog();
        data.add(new DataInput("Datos1", Utilidades.getDouble(txtAmplitud), Utilidades.getDouble(txtCteTiempo), Utilidades.getDouble(txtValorBase), Utilidades.getDouble(txtFrecuencia),Utilidades.getDouble(txtOmega),Color.red));
        Collections.sort(data,data);
        return data;
    }
    
    private void actualiza_omega() {
        double frecuencia = Utilidades.getDouble(txtFrecuencia);
        double omega = Math.round(2*Math.PI*frecuencia);
        Utilidades.setDouble(txtOmega,omega);
    }
    private void actualiza_frecuencia() {
        double omega = Utilidades.getDouble(txtFrecuencia);//Math.round(2*Math.PI*frecuencia);
        double frecuencia = Math.round(omega/2*Math.PI);
        Utilidades.setDouble(txtFrecuencia,frecuencia);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtValorBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmplitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOmega = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCteTiempo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingrese los datos");

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel2.setText("Valor Base");
        jPanel1.add(jLabel2);

        txtValorBase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorBaseFocusGained(evt);
            }
        });
        jPanel1.add(txtValorBase);

        jLabel3.setText("Amplitud");
        jPanel1.add(jLabel3);

        txtAmplitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmplitudFocusGained(evt);
            }
        });
        jPanel1.add(txtAmplitud);

        jLabel4.setText("Frecuencia");
        jPanel1.add(jLabel4);

        txtFrecuencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFrecuenciaFocusGained(evt);
            }
        });
        txtFrecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFrecuenciaKeyReleased(evt);
            }
        });
        jPanel1.add(txtFrecuencia);

        jLabel6.setText("Omega");
        jPanel1.add(jLabel6);

        txtOmega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOmegaFocusGained(evt);
            }
        });
        txtOmega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOmegaKeyReleased(evt);
            }
        });
        jPanel1.add(txtOmega);

        jLabel5.setText("Cte Tiempo");
        jPanel1.add(jLabel5);

        txtCteTiempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCteTiempoFocusGained(evt);
            }
        });
        jPanel1.add(txtCteTiempo);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorBaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorBaseFocusGained
        txtValorBase.selectAll();
    }//GEN-LAST:event_txtValorBaseFocusGained

    private void txtAmplitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmplitudFocusGained
        txtAmplitud.selectAll();
    }//GEN-LAST:event_txtAmplitudFocusGained

    private void txtFrecuenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFrecuenciaFocusGained
        txtFrecuencia.selectAll();
    }//GEN-LAST:event_txtFrecuenciaFocusGained

    private void txtCteTiempoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCteTiempoFocusGained
        txtCteTiempo.selectAll();
    }//GEN-LAST:event_txtCteTiempoFocusGained

    private void txtFrecuenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaKeyReleased
        actualiza_omega();
    }//GEN-LAST:event_txtFrecuenciaKeyReleased

    private void txtOmegaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOmegaFocusGained
        txtOmega.selectAll();
    }//GEN-LAST:event_txtOmegaFocusGained

    private void txtOmegaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOmegaKeyReleased
        actualiza_frecuencia();
    }//GEN-LAST:event_txtOmegaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAmplitud;
    private javax.swing.JTextField txtCteTiempo;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtOmega;
    private javax.swing.JTextField txtValorBase;
    // End of variables declaration//GEN-END:variables

}
